<?php

namespace App\Providers;

use App\DDD\Backoffice\Booking\Domain\Handler\SendConfirmationMailHandler;
use App\DDD\Backoffice\Shared\Domain\Bus\AsyncCommandBusInterface;
use App\DDD\Backoffice\Shared\Domain\Bus\SyncCommandBusInterface;
use App\DDD\Backoffice\Shared\Infrastructure\Bus\LaravelAsyncCommandBus;
use App\DDD\Backoffice\Shared\Infrastructure\Bus\LaravelSyncCommandBus;
use Inertia\ServiceProvider;
use App;

class DDDServiceProvider extends ServiceProvider
{

    protected function __construct()
    {
        // App es un atributo de la clase ServiceProvider
        parent::__construct($this->app);
    }

    public function register(): void {
        // Buses
        $this->app->singleton(
            SyncCommandBusInterface::class,
                    LaravelSyncCommandBus::class
        );

        $this->app->singleton(
            AsyncCommandBusInterface::class,
            LaravelAsyncCommandBus::class
        );

        // Bind de Handlers (a mano, sin magia)
        $this->app->bind(
            SendConfirmationMailHandler::class
        );
    }

    // Esto luego deberá
    public function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
